/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/

/* AI Disclosure: This file was largely AI-generated by Copilot (Claude Sonnet 4.6). */

/**************************************************************************/
/**************************************************************************/
/**                                                                       */
/** USBX Component                                                        */
/**                                                                       */
/**   User Specific — Windows Simulation Port                             */
/**                                                                       */
/**************************************************************************/
/**************************************************************************/


/**************************************************************************/
/*                                                                        */
/*  PORT SPECIFIC C INFORMATION                            RELEASE        */
/*                                                                        */
/*    ux_user_win.h                                      Win32/Win64      */
/*                                                  6.5.2.202603          */
/*                                                                        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens                                                   */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    This file overrides selected USBX configuration constants for the   */
/*    Windows simulation port.  It is included by ux_user.h (which is    */
/*    included when UX_INCLUDE_USER_DEFINE_FILE is defined).              */
/*                                                                        */
/*    This file is intended for test builds only; it is not part of any  */
/*    production configuration.                                           */
/*                                                                        */
/**************************************************************************/

#ifndef UX_USER_WIN_H
#define UX_USER_WIN_H


/* On 64-bit Windows the ABI is LLP64: ULONG is 32 bits while pointers are
   64 bits.  USBX thread/timer entry functions receive control-block pointers
   through a ULONG parameter, which silently truncates the upper 32 bits.
   The UX_THREAD_EXTENSION_PTR_SET/GET and UX_TIMER_EXTENSION_PTR_SET/GET
   hooks work around this by storing the full 64-bit pointer in the TX_THREAD
   / TX_TIMER_INTERNAL extension field (a VOID *) and recovering it via
   tx_thread_identify() / the expired-timer pointer.
   Win32 builds are unaffected: on ILP32/LLP32 ULONG and pointers are both
   32 bits so the default no-op macros in ux_api.h are correct.           */

#ifdef _WIN64

#define UX_THREAD_EXTENSION_PTR_SET(a, b)                   { \
                                                                TX_THREAD *_tx_ptr; \
                                                                _tx_ptr = (TX_THREAD *)(a); \
                                                                (_tx_ptr -> tx_thread_extension_ptr) = (VOID *)(b); \
                                                            }
#define UX_THREAD_EXTENSION_PTR_GET(a, b, c)                { \
                                                                UX_PARAMETER_NOT_USED(c); \
                                                                TX_THREAD *_tx_ptr; \
                                                                _tx_ptr = tx_thread_identify(); \
                                                                while (1) \
                                                                { \
                                                                    if (_tx_ptr -> tx_thread_extension_ptr) \
                                                                    { \
                                                                        (a) = (b *)(_tx_ptr -> tx_thread_extension_ptr); \
                                                                        break; \
                                                                    } \
                                                                    tx_thread_sleep(1); \
                                                                } \
                                                            }
#define UX_TIMER_EXTENSION_PTR_SET(a, b)                    { \
                                                                TX_TIMER *_timer_ptr; \
                                                                _timer_ptr = (TX_TIMER *)(a); \
                                                                (_timer_ptr -> tx_timer_internal.tx_timer_internal_extension_ptr) = (VOID *)(b); \
                                                            }
#define UX_TIMER_EXTENSION_PTR_GET(a, b, c)                 { \
                                                                UX_PARAMETER_NOT_USED(c); \
                                                                if (!_tx_timer_expired_timer_ptr -> tx_timer_internal_extension_ptr) \
                                                                    return; \
                                                                (a) = (b *)(_tx_timer_expired_timer_ptr -> tx_timer_internal_extension_ptr); \
                                                            }

#endif /* _WIN64 */


#endif /* UX_USER_WIN_H */
