/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This tests the bounds on the VideoStreaming format/frame descriptor walks.

   wTotalLength counts the class-specific block from the input header, and the
   walks that serve frame queries start at the selected format instead. The
   budget therefore has to be the block that is left behind that format, held to
   the configuration buffer as well, because both quantities come off the device.  */

#include <stdio.h>
#include "tx_api.h"
#include "ux_api.h"
#include "ux_system.h"
#include "ux_utility.h"
#include "ux_host_class_video.h"

extern void    test_control_return(UINT status);

/* Offsets into the streaming block built below.  */
#define VS_INPUT_HEADER_LENGTH      14
#define VS_FORMAT_LENGTH            11
#define VS_FRAME_LENGTH             30
#define VS_FORMAT_1_OFFSET          VS_INPUT_HEADER_LENGTH
#define VS_FORMAT_2_OFFSET          (VS_FORMAT_1_OFFSET + VS_FORMAT_LENGTH + VS_FRAME_LENGTH)
#define VS_BLOCK_LENGTH             (VS_FORMAT_2_OFFSET + VS_FORMAT_LENGTH + VS_FRAME_LENGTH)

/* Bytes sitting behind the configuration, standing in for whatever the heap holds
   there. A walk that honours the device's reported length instead of the buffer
   reaches them, and they are shaped so that it finds something.  */
#define VS_BEYOND_LENGTH            32
#define VS_PLANTED_FORMAT_INDEX     99
#define VS_PLANTED_FRAME_COUNT      7

/* A VideoStreaming block holding two formats, each with one frame.  The block
   runs to the very end of the configuration, which is what makes the walk from
   the second format shorter than wTotalLength.  */
static UCHAR    streaming_block[VS_BLOCK_LENGTH + VS_BEYOND_LENGTH] = {

    /* VS_INPUT_HEADER: 2 formats, wTotalLength covers the whole block.  */
    VS_INPUT_HEADER_LENGTH, UX_HOST_CLASS_VIDEO_CS_INTERFACE, UX_HOST_CLASS_VIDEO_VS_INPUT_HEADER,
    2, (UCHAR)VS_BLOCK_LENGTH, 0, 0, 0, 0, 0, 0, 0, 0, 0,

    /* VS_FORMAT_MJPEG, format index 1, one frame descriptor.  */
    VS_FORMAT_LENGTH, UX_HOST_CLASS_VIDEO_CS_INTERFACE, UX_HOST_CLASS_VIDEO_VS_FORMAT_MJPEG,
    1, 1, 0, 0, 0, 0, 0, 0,

    /* VS_FRAME_MJPEG, frame index 1, 640x480.  */
    VS_FRAME_LENGTH, UX_HOST_CLASS_VIDEO_CS_INTERFACE, UX_HOST_CLASS_VIDEO_VS_FRAME_MJPEG,
    1, 0, 0x80, 0x02, 0xE0, 0x01, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,

    /* VS_FORMAT_MJPEG, format index 2, one frame descriptor.  */
    VS_FORMAT_LENGTH, UX_HOST_CLASS_VIDEO_CS_INTERFACE, UX_HOST_CLASS_VIDEO_VS_FORMAT_MJPEG,
    2, 1, 0, 0, 0, 0, 0, 0,

    /* VS_FRAME_MJPEG, frame index 1, 320x240.  */
    VS_FRAME_LENGTH, UX_HOST_CLASS_VIDEO_CS_INTERFACE, UX_HOST_CLASS_VIDEO_VS_FRAME_MJPEG,
    1, 0, 0x40, 0x01, 0xF0, 0x00, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,

    /* Past the configuration: a well formed format descriptor that no walk should
       ever reach.  Finding it is the over-read.  */
    VS_FORMAT_LENGTH, UX_HOST_CLASS_VIDEO_CS_INTERFACE, UX_HOST_CLASS_VIDEO_VS_FORMAT_MJPEG,
    VS_PLANTED_FORMAT_INDEX, VS_PLANTED_FRAME_COUNT, 0, 0, 0, 0, 0, 0
};

#define UX_TEST_MEMORY_SIZE     (64 * 1024)

static UX_HOST_CLASS_VIDEO      video_instance;
static UCHAR                    test_memory[UX_TEST_MEMORY_SIZE];

/* A configuration descriptor holding the Video Streaming interface and its input
   header.  _ux_host_class_video_input_format_get scans for the interface, then
   takes the formats length out of the header, so the length has to be reached
   through a walk rather than planted on the instance.  */
#define VS_CFG_INTERFACE_LENGTH     9
#define VS_CFG_HEADER_OFFSET        VS_CFG_INTERFACE_LENGTH
#define VS_CFG_LENGTH               (VS_CFG_INTERFACE_LENGTH + VS_INPUT_HEADER_LENGTH)

static UCHAR    streaming_configuration[VS_CFG_LENGTH] = {

    /* Standard interface descriptor, Video class, Streaming subclass.  */
    VS_CFG_INTERFACE_LENGTH, UX_INTERFACE_DESCRIPTOR_ITEM, 1, 0, 1,
    UX_HOST_CLASS_VIDEO_CLASS, UX_HOST_CLASS_VIDEO_SUBCLASS_STREAMING, 0, 0,

    /* VS_INPUT_HEADER.  wTotalLength is patched per case.  */
    VS_INPUT_HEADER_LENGTH, UX_HOST_CLASS_VIDEO_CS_INTERFACE, UX_HOST_CLASS_VIDEO_VS_INPUT_HEADER,
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};


/* A parse callback that reports the descriptor corrupted, which is what an
   entity parser does when the device's own numbers do not add up.  */
static UINT    parse_reports_corrupted(VOID *arg, UCHAR *packed_interface_descriptor,
                                       UCHAR *packed_entity_descriptor)
{
    UX_PARAMETER_NOT_USED(arg);
    UX_PARAMETER_NOT_USED(packed_interface_descriptor);
    UX_PARAMETER_NOT_USED(packed_entity_descriptor);
    return(UX_DESCRIPTOR_CORRUPTED);
}

/* The entity walk checks the device is configured and matches the streaming
   interface number before it reaches a parser, so both have to exist.  */
static UX_DEVICE        video_device;
static UX_INTERFACE     video_streaming_interface;

/* Point the instance at that configuration and declare a formats length.  */
static VOID    configuration_setup(ULONG total_length)
{

UCHAR   *instance_bytes = (UCHAR *)&video_instance;
ULONG    i;

    for (i = 0; i < (ULONG)sizeof(video_instance); i++)
        instance_bytes[i] = 0;

    video_device.ux_device_state =                                        UX_DEVICE_CONFIGURED;
    video_streaming_interface.ux_interface_descriptor.bInterfaceNumber =  1;
    video_instance.ux_host_class_video_device =                           &video_device;
    video_instance.ux_host_class_video_streaming_interface =              &video_streaming_interface;

    streaming_configuration[VS_CFG_HEADER_OFFSET + 4] = (UCHAR)(total_length & 0xFF);
    streaming_configuration[VS_CFG_HEADER_OFFSET + 5] = (UCHAR)((total_length >> 8) & 0xFF);

    video_instance.ux_host_class_video_configuration_descriptor =         streaming_configuration;
    video_instance.ux_host_class_video_configuration_descriptor_length =  VS_CFG_LENGTH;
}



/* Point the instance at the streaming block, selecting one of its formats.  */
static VOID    video_instance_setup(ULONG format_offset, ULONG length_formats)
{

UCHAR   *instance_bytes = (UCHAR *)&video_instance;
ULONG    i;

    for (i = 0; i < (ULONG)sizeof(video_instance); i++)
        instance_bytes[i] = 0;

    video_instance.ux_host_class_video_configuration_descriptor =         streaming_block;
    video_instance.ux_host_class_video_configuration_descriptor_length =  VS_BLOCK_LENGTH;
    video_instance.ux_host_class_video_format_address =                   streaming_block;
    video_instance.ux_host_class_video_length_formats =                   length_formats;
    video_instance.ux_host_class_video_current_format_address =           streaming_block + format_offset;
}


/* Define what the initial system looks like.  */

#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void usbx_ux_host_class_video_format_walk_bounds_test_application_define(void *first_unused_memory)
#endif
{

UINT                                        status;
UX_HOST_CLASS_VIDEO_PARAMETER_FORMAT_DATA   format_parameter;
UX_HOST_CLASS_VIDEO_PARAMETER_FRAME_DATA    frame_parameter;
UX_HOST_CLASS_VIDEO_PARAMETER_FRAME_INTERVAL
                                            interval_parameter;

    UX_PARAMETER_NOT_USED(first_unused_memory);

    /* Inform user.  */
    printf("Running ux_host_class_video format walk bounds Test.................. ");

    /* The walks report corruption through the system error handler, so the system
       has to be up before any of them runs.  */
    status =  ux_system_initialize(test_memory, UX_TEST_MEMORY_SIZE, UX_NULL, 0);
    if (status != UX_SUCCESS)
    {
        printf("ERROR #%d: system initialize failed (%u)\n", __LINE__, status);
        test_control_return(1);
        return;
    }

    /* The second format sits well inside the block, and the block ends with the
       configuration.  Its frame still has to be found: the budget is the block
       behind the format, not the whole reported formats length.  */
    video_instance_setup(VS_FORMAT_2_OFFSET, VS_BLOCK_LENGTH);
    frame_parameter.ux_host_class_video_parameter_frame_requested = 1;
    status =  _ux_host_class_video_frame_data_get(&video_instance, &frame_parameter);
    if (status != UX_SUCCESS)
    {
        printf("ERROR #%d: frame data get refused a valid second format\n", __LINE__);
        test_control_return(1);
        return;
    }

    if (frame_parameter.ux_host_class_video_parameter_frame_width != 320)
    {
        printf("ERROR #%d: wrong frame width %lu\n", __LINE__,
               frame_parameter.ux_host_class_video_parameter_frame_width);
        test_control_return(1);
        return;
    }

    /* The same holds for the interval query.  */
    video_instance_setup(VS_FORMAT_2_OFFSET, VS_BLOCK_LENGTH);
    interval_parameter.ux_host_class_video_parameter_frame_requested = 1;
    interval_parameter.ux_host_class_video_parameter_frame_interval_buffer = UX_NULL;
    interval_parameter.ux_host_class_video_parameter_frame_interval_buffer_length = 0;
    status =  _ux_host_class_video_frame_interval_get(&video_instance, &interval_parameter);
    if (status != UX_SUCCESS)
    {
        printf("ERROR #%d: frame interval get refused a valid second format\n", __LINE__);
        test_control_return(1);
        return;
    }

    /* A device reporting a formats length past the configuration buffer must be
       refused rather than walked.  */
    video_instance_setup(VS_FORMAT_1_OFFSET, VS_BLOCK_LENGTH * 4);
    frame_parameter.ux_host_class_video_parameter_frame_requested = 99;
    status =  _ux_host_class_video_frame_data_get(&video_instance, &frame_parameter);
    if (status != UX_DESCRIPTOR_CORRUPTED)
    {
        printf("ERROR #%d: oversized formats length was not refused (%u)\n", __LINE__, status);
        test_control_return(1);
        return;
    }

    /* A current format sitting past the reported block is equally corrupt.  */
    video_instance_setup(VS_FORMAT_2_OFFSET, VS_FORMAT_1_OFFSET);
    frame_parameter.ux_host_class_video_parameter_frame_requested = 1;
    status =  _ux_host_class_video_frame_data_get(&video_instance, &frame_parameter);
    if (status != UX_DESCRIPTOR_CORRUPTED)
    {
        printf("ERROR #%d: format past the formats block was not refused (%u)\n", __LINE__, status);
        test_control_return(1);
        return;
    }

    /* The interval query owns the same budget as the frame query, so it has to
       refuse the same two shapes.  */
    video_instance_setup(VS_FORMAT_1_OFFSET, VS_BLOCK_LENGTH * 4);
    interval_parameter.ux_host_class_video_parameter_frame_requested = 99;
    interval_parameter.ux_host_class_video_parameter_frame_interval_buffer = UX_NULL;
    interval_parameter.ux_host_class_video_parameter_frame_interval_buffer_length = 0;
    status =  _ux_host_class_video_frame_interval_get(&video_instance, &interval_parameter);
    if (status != UX_DESCRIPTOR_CORRUPTED)
    {
        printf("ERROR #%d: interval get accepted an oversized formats length (%u)\n", __LINE__, status);
        test_control_return(1);
        return;
    }

    video_instance_setup(VS_FORMAT_2_OFFSET, VS_FORMAT_1_OFFSET);
    interval_parameter.ux_host_class_video_parameter_frame_requested = 1;
    interval_parameter.ux_host_class_video_parameter_frame_interval_buffer = UX_NULL;
    interval_parameter.ux_host_class_video_parameter_frame_interval_buffer_length = 0;
    status =  _ux_host_class_video_frame_interval_get(&video_instance, &interval_parameter);
    if (status != UX_DESCRIPTOR_CORRUPTED)
    {
        printf("ERROR #%d: interval get accepted a format past the block (%u)\n", __LINE__, status);
        test_control_return(1);
        return;
    }

    /* The format query walks from the start of the block rather than from the
       selected format, so its budget is the reported length held to the
       configuration buffer.  A block that ends with the configuration is valid.  */
    video_instance_setup(VS_FORMAT_1_OFFSET, VS_BLOCK_LENGTH);
    format_parameter.ux_host_class_video_parameter_format_requested = 2;
    status =  _ux_host_class_video_format_data_get(&video_instance, &format_parameter);
    if (status != UX_SUCCESS)
    {
        printf("ERROR #%d: format data get refused a valid block (%u)\n", __LINE__, status);
        test_control_return(1);
        return;
    }

    if (format_parameter.ux_host_class_video_parameter_number_frame_descriptors != 1)
    {
        printf("ERROR #%d: wrong frame descriptor count %lu\n", __LINE__,
               format_parameter.ux_host_class_video_parameter_number_frame_descriptors);
        test_control_return(1);
        return;
    }

    /* A reported length past the configuration buffer must be refused before the
       walk dereferences anything.  The format asked for exists only in the bytes
       behind the configuration, so a walk that reaches it reports success and
       hands back a descriptor count it read out of bounds.  */
    video_instance_setup(VS_FORMAT_1_OFFSET, VS_BLOCK_LENGTH + VS_BEYOND_LENGTH);
    format_parameter.ux_host_class_video_parameter_format_requested = VS_PLANTED_FORMAT_INDEX;
    format_parameter.ux_host_class_video_parameter_number_frame_descriptors = 0;
    status =  _ux_host_class_video_format_data_get(&video_instance, &format_parameter);
    if (status != UX_DESCRIPTOR_CORRUPTED)
    {
        printf("ERROR #%d: format data get reached past the configuration (%u, frames %lu)\n",
               __LINE__, status,
               format_parameter.ux_host_class_video_parameter_number_frame_descriptors);
        test_control_return(1);
        return;
    }

    /* The input header's own length field is the one the device controls. A
       header declaring more formats bytes than the configuration holds behind it
       must be refused; before the fix it was taken at face value and the formats
       address published, so every later walk ran on an oversized budget.  */
    configuration_setup(VS_CFG_LENGTH + 0x100);
    status =  _ux_host_class_video_input_format_get(&video_instance);
    if (status != UX_DESCRIPTOR_CORRUPTED)
    {
        printf("ERROR #%d: oversized input header accepted (%u)\n", __LINE__, status);
        test_control_return(1);
        return;
    }

    /* A length that fits is still accepted, and publishes the formats address.  */
    configuration_setup(VS_CFG_LENGTH - VS_CFG_HEADER_OFFSET);
    status =  _ux_host_class_video_input_format_get(&video_instance);
    if (status != UX_SUCCESS)
    {
        printf("ERROR #%d: well formed input header refused (%u)\n", __LINE__, status);
        test_control_return(1);
        return;
    }

    /* A parser that reports corruption has to fail the walk, not merely end it.
       Before the fix any non-zero status stopped the loop and the caller was told
       the parse had succeeded, so a descriptor the parser had already rejected
       went on to be used.  */
    configuration_setup(VS_CFG_LENGTH - VS_CFG_HEADER_OFFSET);
    status =  _ux_host_class_video_entities_parse(&video_instance, parse_reports_corrupted, UX_NULL);
    if (status != UX_DESCRIPTOR_CORRUPTED)
    {
        printf("ERROR #%d: a corrupted parse was reported as success (%u)\n", __LINE__, status);
        test_control_return(1);
        return;
    }

    /* Successful test.  */
    printf("SUCCESS!\n");
    test_control_return(0);
}
