/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Codex (GPT-6-Sol).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

#include <stdio.h>
#include "ux_api.h"
#include "ux_device_class_rndis.h"
#include "ux_test.h"

#define RNDIS_TEST_POOL_SIZE 4096u
#define RNDIS_TEST_PAYLOAD_SIZE 256u
#define RNDIS_TEST_STACK_SIZE 4096u

static TX_THREAD test_thread;
static UCHAR test_stack[RNDIS_TEST_STACK_SIZE];
static UCHAR pool_memory[RNDIS_TEST_POOL_SIZE];
static NX_PACKET_POOL packet_pool;
static UX_SLAVE_CLASS_RNDIS rndis;
static UINT packets_released;
static UINT release_status;

/* Return queued packets to NetX immediately after the RNDIS mutex unlocks. */
static VOID release_queued_packets(UX_TEST_ACTION *action, VOID *params)
{
    NX_PACKET *packet;
    NX_PACKET *next_packet;

    (void)action;
    (void)params;

    packet = rndis.ux_slave_class_rndis_xmit_queue;
    rndis.ux_slave_class_rndis_xmit_queue = UX_NULL;
    while (packet != NX_NULL)
    {
        next_packet = packet -> nx_packet_queue_next;
        if (nx_packet_release(packet) != NX_SUCCESS)
        {
            release_status = UX_ERROR;
        }
        packets_released++;
        packet = next_packet;
    }
}

/* Check that NetX's available count matches every link in its free list. */
static UINT packet_pool_list_is_complete(VOID)
{
    NX_PACKET *packet;
    ULONG count = 0u;

    packet = packet_pool.nx_packet_pool_available_list;
    while ((packet != NX_NULL) && (count <= packet_pool.nx_packet_pool_total))
    {
        count++;
        packet = packet -> nx_packet_queue_next;
    }

    if ((packet != NX_NULL) ||
        (count != packet_pool.nx_packet_pool_available) ||
        (count != packet_pool.nx_packet_pool_total))
    {
        printf("pool free list: %lu entries, %lu available, %lu total\n",
               count, packet_pool.nx_packet_pool_available,
               packet_pool.nx_packet_pool_total);
    }

    return((packet == NX_NULL) &&
           (count == packet_pool.nx_packet_pool_available) &&
           (count == packet_pool.nx_packet_pool_total));
}

/* Exercise dequeue and release after an empty or populated enqueue. */
static UINT run_queue_case(UINT queue_initial_packet)
{
    NX_PACKET *packet;
    UX_TEST_ACTION mutex_hook = {0};
    UINT status;

    if (queue_initial_packet != 0u)
    {
        status = nx_packet_allocate(&packet_pool, &packet, NX_IP_PACKET, NX_NO_WAIT);
        if (status != NX_SUCCESS)
        {
            return(UX_ERROR);
        }
        status = _ux_device_class_rndis_write(&rndis, packet);
        if (status != UX_SUCCESS)
        {
            return(UX_ERROR);
        }
    }

    status = nx_packet_allocate(&packet_pool, &packet, NX_IP_PACKET, NX_NO_WAIT);
    if (status != NX_SUCCESS)
    {
        return(UX_ERROR);
    }

    packets_released = 0u;
    release_status = UX_SUCCESS;
    mutex_hook.usbx_function = UX_TEST_OVERRIDE_TX_MUTEX_PUT;
    mutex_hook.mutex_ptr = &rndis.ux_slave_class_rndis_mutex;
    mutex_hook.do_after = UX_TRUE;
    mutex_hook.action_func = release_queued_packets;
    status = ux_test_link_hook(&mutex_hook);
    if (status != UX_SUCCESS)
    {
        return(UX_ERROR);
    }

    status = _ux_device_class_rndis_write(&rndis, packet);
    ux_test_remove_hook(&mutex_hook);

    if ((status != UX_SUCCESS) || (release_status != UX_SUCCESS) ||
        (packets_released != (queue_initial_packet + 1u)) ||
        (rndis.ux_slave_class_rndis_xmit_queue != UX_NULL) ||
        (packet_pool_list_is_complete() == 0u))
    {
        printf("queue case %u: status %u, release %u, packets %u\n",
               queue_initial_packet, status, release_status, packets_released);
        return(UX_ERROR);
    }
    return(UX_SUCCESS);
}

/* Run both enqueue paths with a real NetX pool and RNDIS synchronization. */
static VOID test_thread_entry(ULONG thread_input)
{
    UINT status;

    (void)thread_input;
    nx_system_initialize();

    status = nx_packet_pool_create(&packet_pool, "RNDIS race pool",
                                   RNDIS_TEST_PAYLOAD_SIZE, pool_memory,
                                   sizeof(pool_memory));
    if (status == NX_SUCCESS)
    {
        status = tx_mutex_create(&rndis.ux_slave_class_rndis_mutex,
                                 "RNDIS race mutex", TX_NO_INHERIT);
    }
    if (status == TX_SUCCESS)
    {
        status = tx_event_flags_create(&rndis.ux_slave_class_rndis_event_flags_group,
                                       "RNDIS race event");
    }
    if (status == TX_SUCCESS)
    {
        status = run_queue_case(0u);
    }
    if (status == UX_SUCCESS)
    {
        status = run_queue_case(1u);
    }

    printf("RNDIS packet queue race: %s\n", status == UX_SUCCESS ? "SUCCESS" : "FAIL");
    test_control_return(status == UX_SUCCESS ? 0u : 1u);
}

/* Start the regression in a ThreadX thread. */
#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void usbx_rndis_packet_queue_race_test_application_define(void *first_unused_memory)
#endif
{
    UINT status;

    (void)first_unused_memory;
    status = tx_thread_create(&test_thread, "RNDIS race test", test_thread_entry,
                              0u, test_stack, sizeof(test_stack), 10u, 10u,
                              TX_NO_TIME_SLICE, TX_AUTO_START);
    if (status != TX_SUCCESS)
    {
        test_control_return(1u);
    }
}
