/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This tests the bounds applied when a HID report descriptor item is analysed.

   An item declares how many data bytes follow its header. The report descriptor
   walk advances by that declaration and parses the data before it checks the
   remaining length, so the analysis itself has to refuse an item whose header
   and data do not fit in what is left of the descriptor.  */

#include <stdio.h>
#include "tx_api.h"
#include "ux_api.h"
#include "ux_system.h"
#include "ux_utility.h"
#include "ux_host_class_hid.h"

extern void    test_control_return(UINT status);

#define UX_TEST_MEMORY_SIZE     (64 * 1024)

static UCHAR                    test_memory[UX_TEST_MEMORY_SIZE];

/* A short item declaring four data bytes, with nothing behind its header.  */
static UCHAR    short_item_overrun[] = { 0x07 };

/* A long item: its header alone is three bytes and it declares four more.  */
static UCHAR    long_item_overrun[] = { 0xF4, 0x04, 0x00 };

/* A well formed USAGE_PAGE item: one header byte and the two bytes it declares.  */
static UCHAR    short_item_exact[] = { 0x06, 0x01, 0xFF };

/* A well formed long item: a three byte header and the two bytes it declares.  */
static UCHAR    long_item_exact[] = { 0xF4, 0x02, 0x00, 0xAA, 0xBB };


/* Define what the initial system looks like.  */

#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void usbx_ux_host_class_hid_report_item_bounds_test_application_define(void *first_unused_memory)
#endif
{

UINT                        status;
UX_HOST_CLASS_HID_ITEM      item;

    UX_PARAMETER_NOT_USED(first_unused_memory);

    /* Inform user.  */
    printf("Running ux_host_class_hid report item bounds Test.................... ");

    /* The analysis reports corruption through the system error handler.  */
    status =  ux_system_initialize(test_memory, UX_TEST_MEMORY_SIZE, UX_NULL, 0);
    if (status != UX_SUCCESS)
    {
        printf("ERROR #%d: system initialize failed (%u)\n", __LINE__, status);
        test_control_return(1);
        return;
    }

    /* A one byte descriptor declaring four data bytes must be refused, otherwise
       the walk advances past the buffer and reads the data that is not there.  */
    status =  _ux_host_class_hid_report_item_analyse(short_item_overrun,
                                                     sizeof(short_item_overrun), &item);
    if (status != UX_DESCRIPTOR_CORRUPTED)
    {
        printf("ERROR #%d: short item overrun accepted (%u)\n", __LINE__, status);
        test_control_return(1);
        return;
    }

    /* The same holds for a long item, whose header is larger again.  */
    status =  _ux_host_class_hid_report_item_analyse(long_item_overrun,
                                                     sizeof(long_item_overrun), &item);
    if (status != UX_DESCRIPTOR_CORRUPTED)
    {
        printf("ERROR #%d: long item overrun accepted (%u)\n", __LINE__, status);
        test_control_return(1);
        return;
    }

    /* An item that fits exactly is still accepted.  */
    status =  _ux_host_class_hid_report_item_analyse(short_item_exact,
                                                     sizeof(short_item_exact), &item);
    if (status != UX_SUCCESS)
    {
        printf("ERROR #%d: well formed item refused (%u)\n", __LINE__, status);
        test_control_return(1);
        return;
    }

    if (item.ux_host_class_hid_item_report_length != 2)
    {
        printf("ERROR #%d: wrong item report length %u\n", __LINE__,
               item.ux_host_class_hid_item_report_length);
        test_control_return(1);
        return;
    }

    /* A long item that fits is accepted, and its header is the three bytes it
       occupies. Reporting the tag mask here instead would have the walks advance
       240 bytes to clear a three byte header.  */
    status =  _ux_host_class_hid_report_item_analyse(long_item_exact,
                                                     sizeof(long_item_exact), &item);
    if (status != UX_SUCCESS)
    {
        printf("ERROR #%d: well formed long item refused (%u)\n", __LINE__, status);
        test_control_return(1);
        return;
    }

    if (item.ux_host_class_hid_item_report_format != 3)
    {
        printf("ERROR #%d: long item header size %u, expected 3\n", __LINE__,
               item.ux_host_class_hid_item_report_format);
        test_control_return(1);
        return;
    }

    /* An empty descriptor has no item in it at all.  */
    status =  _ux_host_class_hid_report_item_analyse(short_item_exact, 0, &item);
    if (status != UX_DESCRIPTOR_CORRUPTED)
    {
        printf("ERROR #%d: empty descriptor accepted (%u)\n", __LINE__, status);
        test_control_return(1);
        return;
    }

    /* Successful test.  */
    printf("SUCCESS!\n");
    test_control_return(0);
}
