/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Codex (GPT-6-Sol).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* Check that each standalone device class has its own task slot. */

#include <stdio.h>
#include "tx_api.h"
#include "ux_api.h"
#include "ux_system.h"
#include "ux_device_stack.h"

static UCHAR usbx_memory[64 * 1024];
static UX_SLAVE_CLASS class_array[3];
static ULONG class_marker;
static UINT dcd_calls;
static UINT skipped_calls;
static UINT task_calls;
static UINT wrong_instance;

void test_control_return(UINT status);

/* Record one device controller task call. */
static UINT test_dcd_entry(UX_SLAVE_DCD *dcd, UINT function, VOID *parameter)
{
    UX_PARAMETER_NOT_USED(dcd);
    UX_PARAMETER_NOT_USED(parameter);

    if (function == UX_DCD_TASKS_RUN)
    {
        dcd_calls++;
    }

    return(UX_SUCCESS);
}

/* Record a task call for an unused class. */
static UINT skipped_class_task(VOID *class_instance)
{
    UX_PARAMETER_NOT_USED(class_instance);
    skipped_calls++;
    return(UX_STATE_NEXT);
}

/* Record the task call for the last registered class. */
static UINT final_class_task(VOID *class_instance)
{
    task_calls++;
    if (class_instance != &class_marker)
    {
        wrong_instance++;
    }
    return(UX_STATE_NEXT);
}

/* Verify that skipped classes do not hide later class tasks. */
void test_application_define(VOID *first_unused_memory)
{
UINT status;

    UX_PARAMETER_NOT_USED(first_unused_memory);
    printf("USBX standalone class task iteration ............................... ");

    status = ux_system_initialize(usbx_memory, sizeof(usbx_memory), UX_NULL, 0);
    if (status != UX_SUCCESS)
    {
        printf("ERROR: system initialization failed\n");
        test_control_return(1);
        return;
    }

    _ux_system_slave -> ux_system_slave_dcd.ux_slave_dcd_function = test_dcd_entry;
    _ux_system_slave -> ux_system_slave_class_array = class_array;
    UX_SYSTEM_DEVICE_MAX_CLASS_SET(3);

    class_array[0].ux_slave_class_status = UX_USED;
    class_array[1].ux_slave_class_status = UX_UNUSED;
    class_array[1].ux_slave_class_task_function = skipped_class_task;
    class_array[2].ux_slave_class_status = UX_USED;
    class_array[2].ux_slave_class_task_function = final_class_task;
    class_array[2].ux_slave_class_instance = &class_marker;

    status = _ux_device_stack_tasks_run();
    if ((status != UX_STATE_NEXT) || (dcd_calls != 1) ||
        (skipped_calls != 0) || (task_calls != 1) || (wrong_instance != 0))
    {
        printf("ERROR: class tasks were not dispatched by slot\n");
        test_control_return(1);
        return;
    }

    printf("SUCCESS!\n");
    test_control_return(0);
}
