# Copyright (C) 2026 Eclipse ThreadX contributors
#
# SPDX-License-Identifier: MIT
#
# Shared helpers for the USBX Win64/Win32 build and test scripts.
# AI Disclosure: This file was largely AI-generated by Copilot (Claude Sonnet 4.6).
# Author: Frédéric Desbiens

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

function Invoke-NativeCommand {
    param(
        [Parameter(Mandatory = $true)]
        [string]$FilePath,

        [Parameter()]
        [string[]]$Arguments = @()
    )

    & $FilePath @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Command failed with exit code ${LASTEXITCODE}: $FilePath $($Arguments -join ' ')"
    }
}

function Get-CommandPathIfAvailable {
    param(
        [Parameter(Mandatory = $true)]
        [string]$CommandName
    )

    $command = Get-Command $CommandName -ErrorAction SilentlyContinue
    if ($null -eq $command) {
        return $null
    }

    return $command.Source
}

function Get-PortSettings {
    param(
        [Parameter(Mandatory = $true)]
        [string]$SelectedArch
    )

    switch ($SelectedArch) {
        'win32' {
            return @{
                UsbxArch      = 'win32'
                UsbxToolchain = 'vs_2019'
                VsArch        = 'x86'
            }
        }
        'win64' {
            return @{
                UsbxArch      = 'win64'
                UsbxToolchain = 'vs_2022'
                VsArch        = 'amd64'
            }
        }
        default {
            throw "Unsupported architecture: $SelectedArch"
        }
    }
}

function Get-RegressionConfigurations {
    return @(
        'default_build_coverage'
    )
}

# Maps a CMake build-type name to a short filesystem-safe directory name.
function Get-ShortConfigName {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ConfigurationName
    )

    $knownNames = @{
        'default_build_coverage'                    = 'dbc'
        'error_check_build_full_coverage'           = 'ecbfc'
        'tracex_enable_build'                       = 'tex'
        'device_buffer_owner_build'                 = 'dbo'
        'device_zero_copy_build'                    = 'dzc'
        'nofx_build_coverage'                       = 'nofx'
        'optimized_build'                           = 'opt'
        'standalone_device_build_coverage'          = 'sad'
        'standalone_device_buffer_owner_build'      = 'sadb'
        'standalone_device_zero_copy_build'         = 'sadz'
        'standalone_host_build_coverage'            = 'sah'
        'standalone_build_coverage'                 = 'sa'
        'generic_build'                             = 'gen'
        'otg_support_build'                         = 'otg'
        'memory_management_build_coverage'          = 'mm'
        'msrc_rtos_build'                           = 'msrcr'
        'msrc_standalone_build'                     = 'msrcsa'
    }

    if ($knownNames.ContainsKey($ConfigurationName)) {
        return $knownNames[$ConfigurationName]
    }

    return $ConfigurationName -replace '[^a-zA-Z0-9_-]', '_'
}

# Generic configuration resolver.
function Resolve-Configurations {
    param(
        [Parameter(Mandatory = $true)]
        [string[]]$ValidConfigurations,

        [Parameter(Mandatory = $false)]
        [AllowNull()]
        [AllowEmptyCollection()]
        [object]$RequestedConfigurations = 'all'
    )

    $resolvedConfigurations = @()

    if ($null -eq $RequestedConfigurations) {
        $resolvedConfigurations = @('all')
    }
    elseif ($RequestedConfigurations -is [System.Array]) {
        foreach ($requestedConfiguration in $RequestedConfigurations) {
            if ($null -ne $requestedConfiguration) {
                $resolvedConfigurations += [string]$requestedConfiguration
            }
        }
    }
    else {
        $resolvedConfigurations = @([string]$RequestedConfigurations)
    }

    $normalizedConfigurations = @()
    foreach ($requestedConfiguration in $resolvedConfigurations) {
        foreach ($configurationPart in ($requestedConfiguration -split ',')) {
            $trimmedConfiguration = $configurationPart.Trim()
            if ($trimmedConfiguration.Length -gt 0) {
                $normalizedConfigurations += $trimmedConfiguration
            }
        }
    }

    if (($normalizedConfigurations.Count -eq 0) -or ($normalizedConfigurations -contains 'all')) {
        return $ValidConfigurations
    }

    foreach ($normalizedConfiguration in $normalizedConfigurations) {
        if ($ValidConfigurations -notcontains $normalizedConfiguration) {
            throw "Unsupported configuration: $normalizedConfiguration"
        }
    }

    return $normalizedConfigurations
}

function Resolve-RegressionConfigurations {
    param(
        [Parameter(Mandatory = $false)]
        [AllowNull()]
        [AllowEmptyCollection()]
        [object]$RequestedConfigurations = 'all'
    )

    return Resolve-Configurations -ValidConfigurations (Get-RegressionConfigurations) `
                                  -RequestedConfigurations $RequestedConfigurations
}

function Get-RegressionBuildDirectoryName {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ConfigurationName
    )

    return Get-ShortConfigName -ConfigurationName $ConfigurationName
}

function Enter-VisualStudioDevShell {
    param(
        [Parameter(Mandatory = $true)]
        [string]$VsArch
    )

    $targetArch = switch ($VsArch) {
        'amd64' { 'x64' }
        'x86'   { 'x86' }
        default { $VsArch }
    }

    if ((Get-Command cl -ErrorAction SilentlyContinue) -and ($env:VSCMD_ARG_TGT_ARCH -eq $targetArch)) {
        return
    }

    $vsWherePath = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer\vswhere.exe'
    if (-not (Test-Path -LiteralPath $vsWherePath)) {
        throw "Unable to locate vswhere.exe at $vsWherePath"
    }

    $installationPath = & $vsWherePath -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
    if (-not $installationPath) {
        throw 'Unable to locate a Visual Studio installation with MSVC build tools.'
    }

    $launchScript = Join-Path $installationPath 'Common7\Tools\Launch-VsDevShell.ps1'
    if (-not (Test-Path -LiteralPath $launchScript)) {
        throw "Unable to locate Launch-VsDevShell.ps1 at $launchScript"
    }

    $env:VSCMD_SKIP_SENDTELEMETRY = '1'
    & $launchScript -VsInstallationPath $installationPath -Arch $VsArch -HostArch amd64 -SkipAutomaticLocation | Out-Null

    if (-not (Get-Command cl -ErrorAction SilentlyContinue)) {
        throw 'MSVC compiler environment was not activated successfully.'
    }
}

function Remove-BuildDirectory {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,

        [Parameter(Mandatory = $true)]
        [string]$RepoRoot
    )

    $fullRepoRoot = [System.IO.Path]::GetFullPath($RepoRoot)
    $fullPath = [System.IO.Path]::GetFullPath($Path)

    if (-not $fullPath.StartsWith($fullRepoRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Refusing to remove a directory outside the repository: $fullPath"
    }

    if (Test-Path -LiteralPath $fullPath) {
        try {
            Remove-Item -LiteralPath $fullPath -Recurse -Force -ErrorAction Stop
            return
        } catch {
            Write-Warning "Failed to remove build directory '$fullPath': $($_.Exception.Message)"
        }

        Get-ChildItem -LiteralPath $fullPath -Force -Recurse -ErrorAction SilentlyContinue | ForEach-Object {
            try {
                if (($_.Attributes -band [System.IO.FileAttributes]::ReadOnly) -ne 0) {
                    $_.Attributes = ($_.Attributes -band (-bnot [System.IO.FileAttributes]::ReadOnly))
                }
            } catch { }
        }

        try {
            Remove-Item -LiteralPath $fullPath -Recurse -Force -ErrorAction Stop
        } catch {
            Write-Warning "Proceeding with partially cleaned build directory '$fullPath': $($_.Exception.Message)"
        }
    }
}

function Remove-CtestTestingDirectory {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        return
    }

    try {
        Remove-Item -LiteralPath $Path -Recurse -Force -ErrorAction Stop
        return
    } catch {
        Write-Warning "Failed to remove CTest directory '$Path': $($_.Exception.Message)"
    }

    Get-ChildItem -LiteralPath $Path -Force -Recurse -ErrorAction SilentlyContinue | ForEach-Object {
        try {
            if (($_.Attributes -band [System.IO.FileAttributes]::ReadOnly) -ne 0) {
                $_.Attributes = ($_.Attributes -band (-bnot [System.IO.FileAttributes]::ReadOnly))
            }
        } catch { }
    }

    try {
        Remove-Item -LiteralPath $Path -Recurse -Force -ErrorAction Stop
    } catch {
        Write-Warning "Proceeding with partially cleaned CTest directory '$Path': $($_.Exception.Message)"
    }
}

function Remove-NinjaLock {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    $ninjaLockPath = Join-Path $Path '.ninja_lock'
    if (Test-Path -LiteralPath $ninjaLockPath) {
        Remove-Item -LiteralPath $ninjaLockPath -Force
    }
}

function Invoke-CMakeBuild {
    param(
        [Parameter(Mandatory = $true)]
        [string]$BuildDir,

        [Parameter()]
        [int]$Parallel = 1,

        [Parameter()]
        [int]$TimeoutSeconds = 600
    )

    $buildToolName = 'Ninja'

    $buildProcess = Start-Process -FilePath 'cmake' `
        -ArgumentList @('--build', $BuildDir, '--parallel', $Parallel.ToString()) `
        -NoNewWindow -PassThru

    $completed = $buildProcess.WaitForExit($TimeoutSeconds * 1000)
    if (-not $completed) {
        $buildProcess.Kill()
        throw "$buildToolName build timed out after ${TimeoutSeconds}s in $BuildDir"
    }

    if ($buildProcess.ExitCode -ne 0) {
        throw "$buildToolName build failed with exit code $($buildProcess.ExitCode) in $BuildDir"
    }
}
