# This is a basic workflow that is manually triggered

name: USBX Regression Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "linux_job"
  run_tests:
    uses: azure-rtos/threadx/.github/workflows/regression_template.yml@master
    with:
      cmake_path: ./test/cmake/usbx
      build_script: ./scripts/build.sh $*
        
